### ISSUE TITLE
Discuss modern comparison operators such as > in addition to .gt.

### ISSUE THREAD

**Issue by Beliavsky** [pranabdas/fortran#1]
I suggest that at https://pranabdas.github.io/fortran/control you mention the comparison operators such as `>, <, ==` etc. introduced in Fortran 90. It's better to use them than `.gt., .lt., .eq.`

Thanks for the tutorial.

**Comment by pranabdas** [comment]
Thank you very much for your suggestion. I have updated my tutorial.
